"""biz six tables

Revision ID: 4f1efe827257
Revises: 
Create Date: 2026-08-18 06:46:42.884931

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f1efe827257'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=32), nullable=False, comment='仓库（华东仓/华北仓/...）'),
    sa.Column('qty', sa.Integer(), nullable=False, comment='在库数量'),
    sa.Column('safety_qty', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='安全库存（低库存评测用）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_product', 'inventory', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='quantity × unit_price，种子勾稽'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_order', 'order_items', ['order_no'], unique=False)
    op.create_index('idx_item_product', 'order_items', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=16), nullable=False, comment='SO-YYYYMMDD-XXXX'),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Enum('华东', '华北', '华南', '西南'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'paid', 'shipped', 'done', 'cancelled'), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='订单总金额 = Σ明细，种子勾稽'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_region', 'orders', ['region'], unique=False)
    op.create_index('idx_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_supplier_created', 'orders', ['supplier_id', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False, comment='SKU-XXXXXXXX'),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False, comment='类目 8 种（电子/机械/包装...）'),
    sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='单价 10–5000'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=16), nullable=False),
    sa.Column('carrier', sa.String(length=32), nullable=False, comment='承运商（顺丰/圆通/中通/德邦...）'),
    sa.Column('tracking_no', sa.String(length=32), nullable=False),
    sa.Column('shipped_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('delivered_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('delay_days', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='延迟发货天数，>0 即延迟（~8% 供日报）'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_ship_order', 'shipments', ['order_no'], unique=False)
    op.create_index('idx_ship_status_shipped', 'shipments', ['shipped_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=16), nullable=False, comment='SUP-XXXX'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.Enum('华东', '华北', '华南', '西南'), nullable=False, comment='华东/华北/华南/西南'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 60–95（种子分布）'),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_index('idx_supplier_region', 'suppliers', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_supplier_region', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('idx_ship_status_shipped', table_name='shipments')
    op.drop_index('idx_ship_order', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_supplier_created', table_name='orders')
    op.drop_index('idx_status_created', table_name='orders')
    op.drop_index('idx_region', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_item_product', table_name='order_items')
    op.drop_index('idx_item_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_inv_product', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
