"""platform core tables

Revision ID: 9e14aff7d28e
Revises: 
Create Date: 2026-08-17 04:55:06.399462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e14aff7d28e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='scm_ 前缀 + 前几位'),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='sha256'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apikey_owner', 'api_keys', ['owner_user_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approval_no', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('diff_before', sa.JSON(), nullable=True),
    sa.Column('diff_after', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_no')
    )
    op.create_index('idx_approval_status_created', 'approvals', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('200'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor_created', 'audit_logs', ['actor', 'created_at'], unique=False)
    op.create_index('idx_audit_event_created', 'audit_logs', ['event', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('est_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('idx_conv_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fb_type', sa.String(length=16), nullable=False, comment='citation / sql'),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_type_created', 'feedback', ['fb_type', 'created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='kb:chat / ops:order:update / data:nl2sql / admin:user:manage'),
    sa.Column('domain', sa.String(length=16), nullable=False, comment='kb / ops / data / admin'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quota_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False, comment='Y-m-d 粒度（令牌桶配额记账）'),
    sa.Column('used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'period')
    )
    op.create_index('idx_quota_period', 'quota_usage', ['period'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='admin / operator / analyst / viewer'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scheduler_job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='防重幂等键'),
    sa.Column('trigger', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('instance', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'run_id')
    )
    op.create_index('idx_jobrun_job_started', 'scheduler_job_runs', ['job_id', 'started_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=97), nullable=False, comment='bcrypt'),
    sa.Column('tenant_id', sa.String(length=32), nullable=False, comment='多租户隔离键'),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_index('idx_jobrun_job_started', table_name='scheduler_job_runs')
    op.drop_table('scheduler_job_runs')
    op.drop_table('roles')
    op.drop_table('role_permissions')
    op.drop_index('idx_quota_period', table_name='quota_usage')
    op.drop_table('quota_usage')
    op.drop_table('permissions')
    op.drop_index('idx_feedback_type_created', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_conv_user_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_audit_event_created', table_name='audit_logs')
    op.drop_index('idx_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_approval_status_created', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('idx_apikey_owner', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
